<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net481</TargetFramework>
		<UseWPF>true</UseWPF>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>

		<LangVersion>12.0</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<ApplicationIcon>128.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ErrorReport>none</ErrorReport>

		<Version>1.0.0.0</Version>
		<Company>Yorii Launcher</Company>
		<Product>Yorii Launcher Installer</Product>
		<Description>Installer for Yorii Launcher</Description>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="128.ico" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System.Net.Http" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Fody" Version="6.8.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Costura.Fody" Version="5.7.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="MicaWPF" Version="7.0.0" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.28000.2270" />
	</ItemGroup>
	<PropertyGroup>
		<SignCertificatePath Condition="'$(SignCertificatePath)'==''"></SignCertificatePath>
		<SignCertificatePassword Condition="'$(SignCertificatePassword)'==''"></SignCertificatePassword>
		<TimestampServer Condition="'$(TimestampServer)'==''">http://timestamp.digicert.com</TimestampServer>
	</PropertyGroup>
	<Target Name="SignOutput" AfterTargets="Build" Condition="'$(SignCertificatePath)'!=''">
		<Exec Command="&quot;$(WindowsSdkDir)bin\$(WindowsSDKVersion)x64\signtool.exe&quot; sign /fd SHA256 /f &quot;$(SignCertificatePath)&quot; /p &quot;$(SignCertificatePassword)&quot; /tr &quot;$(TimestampServer)&quot; /td SHA256 &quot;$(TargetPath)&quot;" />
	</Target>
</Project>

